spring.application.name=ems-backend
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mariadb://localhost:3306/SA
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server.servlet.context-path=/api